language: php
sudo: false

php:
  - '7.0'
  - nightly

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 7
      env: dependencies=lowest
    - php: nightly
      env: dependencies=lowest
    - php: 7
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest

## Update composer and run the appropriate composer command
before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i
